"""Domain layer barrel exports."""

from .alert_derivation import (
    AlertCounts,
    AlertCountsByKey,
    AlertCountsBySeverity,
    ConfirmedDuplicateEvidence,
    DeriveInvoiceAlertsInput,
    InvoiceAlert,
    InvoiceAlertsResult,
    InvoiceTotalMismatchEvidence,
    PossibleDuplicateEvidence,
    SuspiciousOverpaymentEvidence,
    derive_invoice_alerts,
)
from .benchmark_comparison import (
    BenchmarkComparisonSummary,
    BenchmarkLineInput,
    BenchmarkObservationInput,
    ComparableBasis,
    ComparisonAvailable,
    NoCanonicalProduct,
    NoComparableBasis,
    NoObservationsFound,
    NotBenchmarkEligible,
    derive_coverage_tier,
    filter_comparable_observations,
    resolve_benchmark_comparison,
    resolve_invoice_benchmark_comparison,
    summarize_benchmark_results,
)
from .duplicate_suspicion import (
    CandidateEvidence,
    DuplicateSuspicionCandidateInput,
    DuplicateSuspicionResult,
    DuplicateSuspicionTargetInput,
    evaluate_candidate_evidence,
    normalize_invoice_number,
    resolve_duplicate_suspicion,
)
from .entities import (
    CanonicalProduct,
    Farm,
    Invoice,
    InvoiceLineItem,
    InvoiceWithLineItems,
    ProductAlias,
    Supplier,
    UploadedDocument,
)
from .enums import (
    BenchmarkSourceKind,
    CorrectionKind,
    InvoiceStatus,
    LineClassification,
    SourceType,
    StockMovementDirection,
)
from .exact_normalization import (
    ExactNormalizationCandidate,
    NormalizationAmbiguous,
    NormalizationNone,
    NormalizationWinner,
    ResolveExactNormalizationWinnerInput,
    resolve_exact_normalization_winner,
)
from .explanation_derivation import (
    BenchmarkContextRef,
    DeriveInvoiceExplanationsInput,
    DuplicateEvidenceSummaryRef,
    ExplanationCounts,
    ExplanationCountsByKind,
    ExplanationDataUsed,
    ExplanationSourceReferences,
    InvoiceExplanation,
    InvoiceExplanationsResult,
    derive_invoice_explanations,
)
from .invoice_validation import (
    InvoiceValidationResult,
    InvoiceValidationSummary,
    RunInvoiceValidationInput,
    ValidationInvoiceInput,
    ValidationLineItemInput,
    run_invoice_validation,
    summarize_validation_results,
    validate_abnormal_values,
    validate_invoice_total_mismatch,
    validate_line_total_consistency,
    validate_suspicious_unit_price,
)
from .line_classification import (
    ClassificationCounts,
    InvoiceLineClassificationResult,
    LineClassificationInput,
    LineClassificationOutcome,
    classify_invoice_line,
    classify_invoice_lines,
)
from .money import (
    deviation_percent,
    exceeds,
    is_negative,
    is_zero_or_negative,
    median,
    money_abs_diff,
    money_add,
    money_mul,
    money_sub,
    money_within_tolerance,
    to_decimal,
)
from .primitives import UUID, DecimalValue, IsoDateString, IsoTimestampString
from .stock_in_derivation import (
    StockInCounts,
    StockInDerivationResult,
    StockInEligible,
    StockInLineInput,
    StockInSkip,
    StockInValidationGate,
    derive_invoice_stock_in,
    derive_stock_in_outcome,
)

__all__ = [
    # Entities
    "Farm",
    "Supplier",
    "UploadedDocument",
    "Invoice",
    "InvoiceLineItem",
    "CanonicalProduct",
    "ProductAlias",
    "InvoiceWithLineItems",
    # Enums
    "SourceType",
    "InvoiceStatus",
    "LineClassification",
    "BenchmarkSourceKind",
    "StockMovementDirection",
    "CorrectionKind",
    # Primitives
    "UUID",
    "DecimalValue",
    "IsoDateString",
    "IsoTimestampString",
    # Money
    "to_decimal",
    "money_add",
    "money_sub",
    "money_mul",
    "money_abs_diff",
    "money_within_tolerance",
    "is_negative",
    "is_zero_or_negative",
    "exceeds",
    "median",
    "deviation_percent",
    # Benchmark Comparison
    "BenchmarkObservationInput",
    "BenchmarkLineInput",
    "NotBenchmarkEligible",
    "NoCanonicalProduct",
    "NoComparableBasis",
    "NoObservationsFound",
    "ComparableBasis",
    "ComparisonAvailable",
    "BenchmarkComparisonSummary",
    "resolve_benchmark_comparison",
    "resolve_invoice_benchmark_comparison",
    "filter_comparable_observations",
    "derive_coverage_tier",
    "summarize_benchmark_results",
    # Invoice Validation
    "ValidationInvoiceInput",
    "ValidationLineItemInput",
    "RunInvoiceValidationInput",
    "InvoiceValidationResult",
    "InvoiceValidationSummary",
    "run_invoice_validation",
    "validate_line_total_consistency",
    "validate_invoice_total_mismatch",
    "validate_suspicious_unit_price",
    "validate_abnormal_values",
    "summarize_validation_results",
    # Duplicate Suspicion
    "DuplicateSuspicionTargetInput",
    "DuplicateSuspicionCandidateInput",
    "CandidateEvidence",
    "DuplicateSuspicionResult",
    "normalize_invoice_number",
    "evaluate_candidate_evidence",
    "resolve_duplicate_suspicion",
    # Line Classification
    "LineClassificationInput",
    "LineClassificationOutcome",
    "ClassificationCounts",
    "InvoiceLineClassificationResult",
    "classify_invoice_line",
    "classify_invoice_lines",
    # Exact Normalization
    "ExactNormalizationCandidate",
    "ResolveExactNormalizationWinnerInput",
    "NormalizationNone",
    "NormalizationWinner",
    "NormalizationAmbiguous",
    "resolve_exact_normalization_winner",
    # Stock-In Derivation
    "StockInLineInput",
    "StockInValidationGate",
    "StockInEligible",
    "StockInSkip",
    "StockInCounts",
    "StockInDerivationResult",
    "derive_stock_in_outcome",
    "derive_invoice_stock_in",
    # Alert Derivation
    "AlertCounts",
    "AlertCountsBySeverity",
    "AlertCountsByKey",
    "InvoiceAlert",
    "InvoiceAlertsResult",
    "DeriveInvoiceAlertsInput",
    "ConfirmedDuplicateEvidence",
    "PossibleDuplicateEvidence",
    "InvoiceTotalMismatchEvidence",
    "SuspiciousOverpaymentEvidence",
    "derive_invoice_alerts",
    # Explanation Derivation
    "ExplanationDataUsed",
    "BenchmarkContextRef",
    "DuplicateEvidenceSummaryRef",
    "ExplanationSourceReferences",
    "InvoiceExplanation",
    "ExplanationCountsByKind",
    "ExplanationCounts",
    "InvoiceExplanationsResult",
    "DeriveInvoiceExplanationsInput",
    "derive_invoice_explanations",
]
