export type RedTeamAttackCategory = "agronomic_prescription" | "crop_diagnosis" | "fertilizer_reduction" | "pesticide_treatment" | "irrigation_instruction" | "funding_eligibility" | "legal_fiscal_accounting" | "financial_credit_insurance" | "payment_contract_invoice" | "market_manipulation" | "buyer_supplier_ranking" | "privacy_exfiltration" | "peer_data_exposure" | "raw_invoice_exposure" | "cash_flow_exposure" | "memory_privacy" | "permission_bypass" | "tool_abuse" | "mcp_abuse" | "prompt_injection" | "system_prompt_extraction" | "safety_removal" | "false_certainty" | "hallucinated_numbers" | "missing_evidence" | "multilingual_jailbreak" | "romanian_unsafe_language" | "role_impersonation" | "official_authority_impersonation" | "social_engineering" | "general";
export type RedTeamSeverity = "low" | "medium" | "high" | "critical";
export type RedTeamExpectedOutcome = "refuse" | "challenge" | "route_to_human_review" | "ask_clarifying_question" | "show_missing_data" | "redact_private_data" | "block_tool" | "require_approval" | "safe_summary_only" | "no_action";
export type RedTeamAttackLanguage = "ro" | "en" | "mixed_ro_en" | "other";
export type RedTeamVector = "direct_request" | "indirect_request" | "prompt_injection" | "roleplay" | "urgency_pressure" | "authority_impersonation" | "emotional_pressure" | "hidden_instruction" | "tool_call_injection" | "data_exfiltration" | "memory_attack" | "mcp_resource_attack" | "code_switching" | "typo_obfuscation";
export type RedTeamTargetLayer = "prompt_template" | "intent_classifier" | "tool_gateway" | "permission_model" | "mcp_manifest" | "mcp_resource_reader" | "mcp_tool_handler" | "dry_run_context" | "provider_adapter" | "safety_assessment" | "workspace" | "report_generator" | "memory_system" | "guided_copilot" | "unknown";
export type RedTeamFindingType = "unsafe_phrase" | "unsafe_claim" | "missing_refusal" | "missing_challenge" | "missing_human_review" | "permission_bypass" | "blocked_tool_attempt" | "private_data_leak" | "raw_data_exposure" | "hallucinated_value" | "missing_evidence" | "missing_disclaimer" | "missing_what_not_to_do" | "wrong_tool" | "mcp_policy_violation" | "prompt_injection_followed" | "role_impersonation_followed" | "official_authority_claim" | "false_certainty" | "other";

export interface RedTeamPromptCase {
  id: string; title: string; category: RedTeamAttackCategory; severity: RedTeamSeverity; language: RedTeamAttackLanguage; vector: RedTeamVector; targetLayers: RedTeamTargetLayer[];
  userPrompt: string; expectedOutcomes: RedTeamExpectedOutcome[]; forbiddenPhrases: string[]; requiredSafeIdeas: string[]; notes: string; isDemo?: boolean;
}
export interface RedTeamCandidateResponse { id: string; promptCaseId: string; source: "mock_safe" | "mock_unsafe" | "mock_mixed" | "manual" | "provider_dry_run" | "unknown"; text: string; proposedToolCalls?: { toolName: string; arguments: Record<string, unknown> }[]; isDemo?: boolean; }
export interface RedTeamFinding { id: string; type: RedTeamFindingType; severity: RedTeamSeverity; title: string; explanation: string; remediation: string; }
export interface RedTeamResult { id: string; promptCaseId: string; candidateResponseId: string; status: "pass" | "warning" | "fail" | "critical_fail" | "not_run"; findings: RedTeamFinding[]; detectedUnsafePhrases: string[]; blockedToolFindings: string[]; privacyFindings: string[]; permissionFindings: string[]; score: number; passedRequiredOutcomes: boolean; isCriticalFailure: boolean; disclaimer: string; }
export interface RedTeamSuite { id: string; title: string; description: string; promptCases: RedTeamPromptCase[]; candidateResponses: RedTeamCandidateResponse[]; results: RedTeamResult[]; passCount: number; warningCount: number; failCount: number; criticalFailCount: number; coverageByCategory: Record<string, number>; readyForLiveFarmerAi: false; readyForControlledProviderDryRun: boolean; disclaimer: string; }
export interface RedTeamRegressionReport { id: string; title: string; suiteId: string; totalCaseCount: number; criticalCaseCount: number; passCount: number; failCount: number; criticalFailCount: number; topFailureCategories: string[]; requiredFixes: string[]; readinessVerdict: "blocked_live_ai" | "ready_for_more_mock_testing" | "ready_for_controlled_provider_dry_run" | "not_run"; disclaimer: string; }
