"""initial schema

Revision ID: f6c1486c14e1
Revises: 
Create Date: 2026-04-03 18:28:38.619411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6c1486c14e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_corrections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('invoice_line_item_id', sa.UUID(), nullable=False),
    sa.Column('correction_kind', sa.Enum('CANONICAL_PRODUCT_REASSIGNMENT', name='correction_kind', create_constraint=True), nullable=False),
    sa.Column('previous_canonical_product_id', sa.UUID(), nullable=True),
    sa.Column('new_canonical_product_id', sa.UUID(), nullable=False),
    sa.Column('previous_normalization_method', sa.String(), nullable=True),
    sa.Column('previous_normalization_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('previous_raw_description', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['invoice_line_item_id'], ['invoice_line_items.id'], ),
    sa.ForeignKeyConstraint(['new_canonical_product_id'], ['canonical_products.id'], ),
    sa.ForeignKeyConstraint(['previous_canonical_product_id'], ['canonical_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_line_corrections_created_at', 'line_corrections', ['created_at'], unique=False)
    op.create_index('ix_line_corrections_farm_id', 'line_corrections', ['farm_id'], unique=False)
    op.create_index('ix_line_corrections_invoice_id', 'line_corrections', ['invoice_id'], unique=False)
    op.create_index('ix_line_corrections_invoice_line_item_id', 'line_corrections', ['invoice_line_item_id'], unique=False)
    op.alter_column('benchmark_observations', 'region_county',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('benchmark_observations', 'region_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('benchmark_observations', 'normalized_unit',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('benchmark_observations', 'currency',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'RON'::text"))
    op.drop_index(op.f('benchmark_observations_canonical_product_id_idx'), table_name='benchmark_observations')
    op.drop_index(op.f('benchmark_observations_farm_id_idx'), table_name='benchmark_observations')
    op.drop_index(op.f('benchmark_observations_observed_at_idx'), table_name='benchmark_observations')
    op.drop_index(op.f('benchmark_observations_source_kind_idx'), table_name='benchmark_observations')
    op.create_index('ix_benchmark_observations_canonical_product_id', 'benchmark_observations', ['canonical_product_id'], unique=False)
    op.create_index('ix_benchmark_observations_farm_id', 'benchmark_observations', ['farm_id'], unique=False)
    op.create_index('ix_benchmark_observations_observed_at', 'benchmark_observations', ['observed_at'], unique=False)
    op.create_index('ix_benchmark_observations_source_kind', 'benchmark_observations', ['source_kind'], unique=False)
    op.alter_column('canonical_products', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('canonical_products', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('canonical_products', 'default_unit',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('farms', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'unit',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'normalization_method',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('invoice_line_items_invoice_id_idx'), table_name='invoice_line_items')
    op.drop_index(op.f('invoice_line_items_invoice_id_line_order_idx'), table_name='invoice_line_items')
    op.create_index('ix_invoice_line_items_invoice_id', 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_unique_constraint('uq_invoice_line_items_invoice_id_line_order', 'invoice_line_items', ['invoice_id', 'line_order'])
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('invoices', 'currency',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'RON'::text"))
    op.alter_column('invoices', 'raw_extraction_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('invoices', 'extraction_method',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('invoices_farm_id_idx'), table_name='invoices')
    op.drop_index(op.f('invoices_supplier_id_idx'), table_name='invoices')
    op.drop_index(op.f('invoices_uploaded_document_id_idx'), table_name='invoices')
    op.create_index('ix_invoices_farm_id', 'invoices', ['farm_id'], unique=False)
    op.create_index('ix_invoices_supplier_id', 'invoices', ['supplier_id'], unique=False)
    op.create_unique_constraint('uq_invoices_uploaded_document_id', 'invoices', ['uploaded_document_id'])
    op.alter_column('product_aliases', 'alias_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('product_aliases', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('product_aliases_alias_text_idx'), table_name='product_aliases')
    op.drop_index(op.f('product_aliases_canonical_product_id_idx'), table_name='product_aliases')
    op.create_index('ix_product_aliases_alias_text', 'product_aliases', ['alias_text'], unique=False)
    op.create_index('ix_product_aliases_canonical_product_id', 'product_aliases', ['canonical_product_id'], unique=False)
    op.alter_column('stock_movements', 'unit',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('stock_movements', 'idempotency_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('stock_movements_canonical_product_id_idx'), table_name='stock_movements')
    op.drop_index(op.f('stock_movements_effective_at_idx'), table_name='stock_movements')
    op.drop_constraint(op.f('stock_movements_farm_id_idempotency_key_unq'), 'stock_movements', type_='unique')
    op.drop_index(op.f('stock_movements_farm_id_idx'), table_name='stock_movements')
    op.drop_index(op.f('stock_movements_invoice_id_idx'), table_name='stock_movements')
    op.create_index('ix_stock_movements_canonical_product_id', 'stock_movements', ['canonical_product_id'], unique=False)
    op.create_index('ix_stock_movements_effective_at', 'stock_movements', ['effective_at'], unique=False)
    op.create_index('ix_stock_movements_farm_id', 'stock_movements', ['farm_id'], unique=False)
    op.create_index('ix_stock_movements_invoice_id', 'stock_movements', ['invoice_id'], unique=False)
    op.create_unique_constraint('uq_stock_movements_farm_id_idempotency_key', 'stock_movements', ['farm_id', 'idempotency_key'])
    op.alter_column('suppliers', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('suppliers', 'tax_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('suppliers_farm_id_idx'), table_name='suppliers')
    op.drop_constraint(op.f('suppliers_id_farm_id_unq'), 'suppliers', type_='unique')
    op.create_index('ix_suppliers_farm_id', 'suppliers', ['farm_id'], unique=False)
    op.create_unique_constraint('uq_suppliers_id_farm_id', 'suppliers', ['id', 'farm_id'])
    op.alter_column('uploaded_documents', 'original_filename',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('uploaded_documents', 'storage_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('uploaded_documents', 'mime_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('uploaded_documents_farm_id_idx'), table_name='uploaded_documents')
    op.drop_constraint(op.f('uploaded_documents_id_farm_id_unq'), 'uploaded_documents', type_='unique')
    op.create_index('ix_uploaded_documents_farm_id', 'uploaded_documents', ['farm_id'], unique=False)
    op.create_unique_constraint('uq_uploaded_documents_id_farm_id', 'uploaded_documents', ['id', 'farm_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_uploaded_documents_id_farm_id', 'uploaded_documents', type_='unique')
    op.drop_index('ix_uploaded_documents_farm_id', table_name='uploaded_documents')
    op.create_unique_constraint(op.f('uploaded_documents_id_farm_id_unq'), 'uploaded_documents', ['id', 'farm_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('uploaded_documents_farm_id_idx'), 'uploaded_documents', ['farm_id'], unique=False)
    op.alter_column('uploaded_documents', 'mime_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('uploaded_documents', 'storage_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('uploaded_documents', 'original_filename',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_suppliers_id_farm_id', 'suppliers', type_='unique')
    op.drop_index('ix_suppliers_farm_id', table_name='suppliers')
    op.create_unique_constraint(op.f('suppliers_id_farm_id_unq'), 'suppliers', ['id', 'farm_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('suppliers_farm_id_idx'), 'suppliers', ['farm_id'], unique=False)
    op.alter_column('suppliers', 'tax_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('suppliers', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_stock_movements_farm_id_idempotency_key', 'stock_movements', type_='unique')
    op.drop_index('ix_stock_movements_invoice_id', table_name='stock_movements')
    op.drop_index('ix_stock_movements_farm_id', table_name='stock_movements')
    op.drop_index('ix_stock_movements_effective_at', table_name='stock_movements')
    op.drop_index('ix_stock_movements_canonical_product_id', table_name='stock_movements')
    op.create_index(op.f('stock_movements_invoice_id_idx'), 'stock_movements', ['invoice_id'], unique=False)
    op.create_index(op.f('stock_movements_farm_id_idx'), 'stock_movements', ['farm_id'], unique=False)
    op.create_unique_constraint(op.f('stock_movements_farm_id_idempotency_key_unq'), 'stock_movements', ['farm_id', 'idempotency_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('stock_movements_effective_at_idx'), 'stock_movements', ['effective_at'], unique=False)
    op.create_index(op.f('stock_movements_canonical_product_id_idx'), 'stock_movements', ['canonical_product_id'], unique=False)
    op.alter_column('stock_movements', 'idempotency_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('stock_movements', 'unit',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('ix_product_aliases_canonical_product_id', table_name='product_aliases')
    op.drop_index('ix_product_aliases_alias_text', table_name='product_aliases')
    op.create_index(op.f('product_aliases_canonical_product_id_idx'), 'product_aliases', ['canonical_product_id'], unique=False)
    op.create_index(op.f('product_aliases_alias_text_idx'), 'product_aliases', ['alias_text'], unique=False)
    op.alter_column('product_aliases', 'source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('product_aliases', 'alias_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_invoices_uploaded_document_id', 'invoices', type_='unique')
    op.drop_index('ix_invoices_supplier_id', table_name='invoices')
    op.drop_index('ix_invoices_farm_id', table_name='invoices')
    op.create_index(op.f('invoices_uploaded_document_id_idx'), 'invoices', ['uploaded_document_id'], unique=True)
    op.create_index(op.f('invoices_supplier_id_idx'), 'invoices', ['supplier_id'], unique=False)
    op.create_index(op.f('invoices_farm_id_idx'), 'invoices', ['farm_id'], unique=False)
    op.alter_column('invoices', 'extraction_method',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('invoices', 'raw_extraction_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('invoices', 'currency',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'RON'::text"))
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_invoice_line_items_invoice_id_line_order', 'invoice_line_items', type_='unique')
    op.drop_index('ix_invoice_line_items_invoice_id', table_name='invoice_line_items')
    op.create_index(op.f('invoice_line_items_invoice_id_line_order_idx'), 'invoice_line_items', ['invoice_id', 'line_order'], unique=True)
    op.create_index(op.f('invoice_line_items_invoice_id_idx'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.alter_column('invoice_line_items', 'normalization_method',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'unit',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('farms', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('canonical_products', 'default_unit',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('canonical_products', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('canonical_products', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('ix_benchmark_observations_source_kind', table_name='benchmark_observations')
    op.drop_index('ix_benchmark_observations_observed_at', table_name='benchmark_observations')
    op.drop_index('ix_benchmark_observations_farm_id', table_name='benchmark_observations')
    op.drop_index('ix_benchmark_observations_canonical_product_id', table_name='benchmark_observations')
    op.create_index(op.f('benchmark_observations_source_kind_idx'), 'benchmark_observations', ['source_kind'], unique=False)
    op.create_index(op.f('benchmark_observations_observed_at_idx'), 'benchmark_observations', ['observed_at'], unique=False)
    op.create_index(op.f('benchmark_observations_farm_id_idx'), 'benchmark_observations', ['farm_id'], unique=False)
    op.create_index(op.f('benchmark_observations_canonical_product_id_idx'), 'benchmark_observations', ['canonical_product_id'], unique=False)
    op.alter_column('benchmark_observations', 'currency',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'RON'::text"))
    op.alter_column('benchmark_observations', 'normalized_unit',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('benchmark_observations', 'region_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('benchmark_observations', 'region_county',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index('ix_line_corrections_invoice_line_item_id', table_name='line_corrections')
    op.drop_index('ix_line_corrections_invoice_id', table_name='line_corrections')
    op.drop_index('ix_line_corrections_farm_id', table_name='line_corrections')
    op.drop_index('ix_line_corrections_created_at', table_name='line_corrections')
    op.drop_table('line_corrections')
    # ### end Alembic commands ###
